###################
wrapper:
###################
    seed: 42
    min_epochs: 0
    max_epochs: 20
    find_unused_parameters: True
    flip_lr_prob: 0.5
    validate_flipped: True
    validate_first: True
    sync_batch_norm: True
    align_corners: False
    clip_grad_value: 10.0
    use_tf32: True
    debug: True
###################
arch:
###################
    model:
###################
        file: generic/GenericModel
        params:
            intrinsics:
                use_gt: True
            pose:
                use_gt: True
            perceiver:
                inputs: [rgb,intrinsics]
                targets: target
                encodes: target
                losses: target
###################
    networks:
###################
        perceiver:
            file: perceiver/ZeroDepthNet
            checkpoint: /data/models/ZeroDepth_outdoor.ckpt
            sample_encoder: [0.5,1.0,1.0]
            sample_decoder: 8
            downsample_encoder: 4
            downsample_decoder: 1
            shake_encoder: True
            shake_decoder: True
            encode_sources: [[camera,image]]
            decode_sources: [['',0,mod,[camera],[depth]]]
            encode_augmentation:
                resize: [[0.25,1.5,32],[0.25,1.5,32]]
            variational:
                kld_weight: 0.1
                n_train_samples: 1
                n_validation_samples: 10
                encode_vae: [True]
            mode: default
            latent:
                num: 1024
                dim: 1024
            encoder:
                use_query_residual: True
                hidden_activ: gelu
                attention_dropout: 0.1
                num_blocks: 1
                num_self_attends_per_block: 8
                self_attention:
                    num_heads: 8
                    widening_factor: 1
                cross_attention:
                    num_heads: 1
                    widening_factor: 1
            embeddings:
                image:
                    type: resnet18_all-4
                camera:
                    to_world: False
                    rays:
                        num_bands: 16
                        max_resolution: 64
            decoders:
                shared:
                    hidden_activ: gelu
                    use_query_residual: False
                    attention_dropout: 0.1
                    widening_factor: 1
                    upsample_mode: convex
                    upsample_value: 1
                    num_heads: 1
                depth:
                    output_num_channels: 1
                    depth_range: [0.1,200.0]
                    output_mode: inv_depth
###################
recipe_evaluation: evaluation/zerodepth|outdoor
##################
datasets:
###################
    validation:
###################
        external: [True]
        datasets: [
            validation_kitti,
            # validation_ddad,
            # validation_nuscenes,
        ]
        context: []
        labels: [intrinsics,depth]
        labels_context: [intrinsics,depth]
        dataloader:
            pin_memory: True
            num_workers: 16
            batch_size: 4
###################
    validation_kitti:
        evaluation:
            metrics: [depth|kitti_resize]
        name: [KITTI]
        path: [/data/datasets/KITTI_tiny]
        split: [kitti_tiny.txt]
        augmentation:
            resize: [192,640]
        depth_type: [velodyne]
        cameras: [[0]]
        single_intrinsics: [True]
        dataloader:
            batch_size: 1
###################
    validation_ddad:
        evaluation:
            metrics: [depth|ddad]
        name: [Ourawboros]
        path: [/data/datasets/DDAD/ddad.json]
        split: [val]
        augmentation:
            resize: [384,640]
        depth_type: [lidar]
        cameras: [[1],[5],[6],[7],[8],[9]]
        prefix: [CAMERA]
###################
    validation_nuscenes:
        evaluation:
            metrics: [depth|nuscenes]
        name: [NuScenes]
        path: [/data/datasets/nuscenes]
        split: [val]
        augmentation:
            resize: [384,640]
        keyframe_only: [True]
        depth_type: [lidar]
        cameras: [[0],[1],[2],[3],[4],[5]]
###################
