###################
networks:
###################
    perceiver:
        file: perceiver/ZeroDepthNet
        sample_decoder: 8
        downsample_encoder: 4
        downsample_decoder: 1
        encode_sources: [[camera,image]]
        decode_sources: [['',0,mod,[camera],[depth]]]
        variational:
            kld_weight: 0.1
            n_train_samples: 1
            n_validation_samples: 10
            encode_vae: [True]
        mode: default
        latent:
            num: 1024
            dim: 1024
        encoder:
            use_query_residual: True
            hidden_activ: gelu
            attention_dropout: 0.1
            num_blocks: 1
            num_self_attends_per_block: 8
            self_attention:
                num_heads: 8
                widening_factor: 1
            cross_attention:
                num_heads: 1
                widening_factor: 1
        embeddings:
            image:
                type: resnet18_all-4
            camera:
                to_world: False
                rays:
                    num_bands: 16
                    max_resolution: 64
        decoders:
            shared:
                hidden_activ: gelu
                use_query_residual: False
                attention_dropout: 0.1
                widening_factor: 1
                upsample_mode: convex
                upsample_value: 1
                num_heads: 1
            depth:
                output_num_channels: 1
                depth_range: [0.1,200.0]
                output_mode: inv_depth