wrapper:
    recipe: wrapper|default_flip
arch:
    model:
        file: depth/SelfSupervisedModel
        checkpoint: /data/models/papers/PackNet_MR_selfsup_KITTI.ckpt
    networks:
        depth:
            recipe: networks/packnet|default
            depth_range: [0.1,100.0]
        pose:
            recipe: networks/conv_pose_net|default
evaluation:
    depth:
        recipe: evaluation/depth|kitti_resize
datasets:
    validation:
        recipe: datasets/kitti_tiny|val_velodyne_MR
save:
    recipe: save|depth_splitname
